blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions & General Discussion
    url: https://github.com/ruma-ui/ui/discussions
    about: Please ask questions and participate in discussions
